
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-sqlite'
import { sqliteTable, index, uniqueIndex, foreignKey, integer, text, numeric } from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const users_sessions = sqliteTable('users_sessions', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: text('id').primaryKey(),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  expiresAt: text('expires_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('users_sessions_order_idx').on(columns._order), index('users_sessions_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const users = sqliteTable('users', {
  id: integer('id').primaryKey(),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  email: text('email').notNull(),
  resetPasswordToken: text('reset_password_token'),
  resetPasswordExpiration: text('reset_password_expiration').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  salt: text('salt'),
  hash: text('hash'),
  loginAttempts: numeric('login_attempts', {mode: 'number'}).default(0),
  lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt), index('users_created_at_idx').on(columns.createdAt), uniqueIndex('users_email_idx').on(columns.email),
]
)


export const media = sqliteTable('media', {
  id: integer('id').primaryKey(),
  alt: text('alt').notNull(),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  url: text('url'),
  thumbnailURL: text('thumbnail_u_r_l'),
  filename: text('filename'),
  mimeType: text('mime_type'),
  filesize: numeric('filesize', {mode: 'number'}),
  width: numeric('width', {mode: 'number'}),
  height: numeric('height', {mode: 'number'}),
  focalX: numeric('focal_x', {mode: 'number'}),
  focalY: numeric('focal_y', {mode: 'number'}),
}, (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt), index('media_created_at_idx').on(columns.createdAt), uniqueIndex('media_filename_idx').on(columns.filename),
]
)


export const guest_sessions = sqliteTable('guest_sessions', {
  id: integer('id').primaryKey(),
  guestId: text('guest_id').notNull(),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  lastActiveAt: text('last_active_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  expiresAt: text('expires_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  locale: text('locale', {enum: ['es', 'en']}),
  theme: text('theme', {enum: ['light', 'dark', 'system']}).default("system"),
  notificationsEnabled: integer('notifications_enabled', {mode: 'boolean'}).default(true),
  integrations: text('integrations', {mode: 'json'}),
  focusSettings: text('focus_settings', {mode: 'json'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('guest_sessions_guest_id_idx').on(columns.guestId), index('guest_sessions_updated_at_idx').on(columns.updatedAt),
]
)


export const lists = sqliteTable('lists', {
  id: integer('id').primaryKey(),
  name: text('name').notNull(),
  icon: text('icon').default("list"),
  color: text('color'),
  guestId: text('guest_id').notNull(),
  isDefault: integer('is_default', {mode: 'boolean'}).default(false),
  sortOrder: numeric('sort_order', {mode: 'number'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('lists_guest_id_idx').on(columns.guestId), index('lists_updated_at_idx').on(columns.updatedAt), index('lists_created_at_idx').on(columns.createdAt),
]
)


export const tasks_subtasks = sqliteTable('tasks_subtasks', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  completed: integer('completed', {mode: 'boolean'}).default(false),
}, (columns) => [
    index('tasks_subtasks_order_idx').on(columns._order), index('tasks_subtasks_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tasks.id],
      name: 'tasks_subtasks_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const tasks = sqliteTable('tasks', {
  id: integer('id').primaryKey(),
  title: text('title').notNull(),
  description: text('description'),
  status: text('status', {enum: ['pending', 'completed']}).notNull().default("pending"),
  important: integer('important', {mode: 'boolean'}).default(false),
  dueDate: text('due_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  list: integer('list_id').references(() => lists.id, {
      onDelete: 'set null'
  }),
  guestId: text('guest_id').notNull(),
  sortOrder: numeric('sort_order', {mode: 'number'}),
  completedAt: text('completed_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('tasks_list_idx').on(columns.list), index('tasks_guest_id_idx').on(columns.guestId), index('tasks_updated_at_idx').on(columns.updatedAt), index('tasks_created_at_idx').on(columns.createdAt),
]
)


export const task_logs = sqliteTable('task_logs', {
  id: integer('id').primaryKey(),
  task: text('task').notNull(),
  guestId: text('guest_id').notNull(),
  operation: text('operation', {enum: ['CREATE', 'UPDATE', 'DELETE']}).notNull(),
  previousState: text('previous_state', {mode: 'json'}),
  newState: text('new_state', {mode: 'json'}),
  timestamp: text('timestamp').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('task_logs_task_idx').on(columns.task), index('task_logs_updated_at_idx').on(columns.updatedAt), index('task_logs_created_at_idx').on(columns.createdAt),
]
)


export const focus_sessions = sqliteTable('focus_sessions', {
  id: integer('id').primaryKey(),
  guestId: text('guest_id').notNull(),
  duration: numeric('duration', {mode: 'number'}).notNull(),
  completed: integer('completed', {mode: 'boolean'}).default(false),
  completedAt: text('completed_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  date: text('date').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('focus_sessions_guest_id_idx').on(columns.guestId), index('focus_sessions_updated_at_idx').on(columns.updatedAt), index('focus_sessions_created_at_idx').on(columns.createdAt),
]
)


export const payload_kv = sqliteTable('payload_kv', {
  id: integer('id').primaryKey(),
  key: text('key').notNull(),
  data: text('data', {mode: 'json'}).notNull(),
}, (columns) => [
    uniqueIndex('payload_kv_key_idx').on(columns.key),
]
)


export const payload_locked_documents = sqliteTable('payload_locked_documents', {
  id: integer('id').primaryKey(),
  globalSlug: text('global_slug'),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug), index('payload_locked_documents_updated_at_idx').on(columns.updatedAt), index('payload_locked_documents_created_at_idx').on(columns.createdAt),
]
)


export const payload_locked_documents_rels = sqliteTable('payload_locked_documents_rels', {
  id: integer('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: text('path').notNull(),
  usersID: integer('users_id'),
  mediaID: integer('media_id'),
  'guest-sessionsID': integer('guest_sessions_id'),
  listsID: integer('lists_id'),
  tasksID: integer('tasks_id'),
  'task-logsID': integer('task_logs_id'),
  'focus-sessionsID': integer('focus_sessions_id'),
}, (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order), index('payload_locked_documents_rels_parent_idx').on(columns.parent), index('payload_locked_documents_rels_path_idx').on(columns.path), index('payload_locked_documents_rels_users_id_idx').on(columns.usersID), index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID), index('payload_locked_documents_rels_guest_sessions_id_idx').on(columns['guest-sessionsID']), index('payload_locked_documents_rels_lists_id_idx').on(columns.listsID), index('payload_locked_documents_rels_tasks_id_idx').on(columns.tasksID), index('payload_locked_documents_rels_task_logs_id_idx').on(columns['task-logsID']), index('payload_locked_documents_rels_focus_sessions_id_idx').on(columns['focus-sessionsID']), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['guest-sessionsID']],
      foreignColumns: [guest_sessions.id],
      name: 'payload_locked_documents_rels_guest_sessions_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['listsID']],
      foreignColumns: [lists.id],
      name: 'payload_locked_documents_rels_lists_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['tasksID']],
      foreignColumns: [tasks.id],
      name: 'payload_locked_documents_rels_tasks_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['task-logsID']],
      foreignColumns: [task_logs.id],
      name: 'payload_locked_documents_rels_task_logs_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['focus-sessionsID']],
      foreignColumns: [focus_sessions.id],
      name: 'payload_locked_documents_rels_focus_sessions_fk'
    }).onDelete('cascade'),
]
)


export const payload_preferences = sqliteTable('payload_preferences', {
  id: integer('id').primaryKey(),
  key: text('key'),
  value: text('value', {mode: 'json'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_preferences_key_idx').on(columns.key), index('payload_preferences_updated_at_idx').on(columns.updatedAt), index('payload_preferences_created_at_idx').on(columns.createdAt),
]
)


export const payload_preferences_rels = sqliteTable('payload_preferences_rels', {
  id: integer('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: text('path').notNull(),
  usersID: integer('users_id'),
}, (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order), index('payload_preferences_rels_parent_idx').on(columns.parent), index('payload_preferences_rels_path_idx').on(columns.path), index('payload_preferences_rels_users_id_idx').on(columns.usersID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk'
    }).onDelete('cascade'),
]
)


export const payload_migrations = sqliteTable('payload_migrations', {
  id: integer('id').primaryKey(),
  name: text('name'),
  batch: numeric('batch', {mode: 'number'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt), index('payload_migrations_created_at_idx').on(columns.createdAt),
]
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
    }),
      }))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
            relationName: 'sessions',
    }),
      }))
export const relations_media = relations(media, () => ({
  
      }))
export const relations_guest_sessions = relations(guest_sessions, () => ({
  
      }))
export const relations_lists = relations(lists, () => ({
  
      }))
export const relations_tasks_subtasks = relations(tasks_subtasks, ({ one }) => ({
  _parentID: one(tasks, {
    
    fields: [tasks_subtasks._parentID],
    references: [tasks.id],
    relationName: 'subtasks',
    }),
      }))
export const relations_tasks = relations(tasks, ({ one, many }) => ({
  list: one(lists, {
    
    fields: [tasks.list],
    references: [lists.id],
    relationName: 'list',
    }),
    subtasks: many(tasks_subtasks, {
            relationName: 'subtasks',
    }),
      }))
export const relations_task_logs = relations(task_logs, () => ({
  
      }))
export const relations_focus_sessions = relations(focus_sessions, () => ({
  
      }))
export const relations_payload_kv = relations(payload_kv, () => ({
  
      }))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
    mediaID: one(media, {
    
    fields: [payload_locked_documents_rels.mediaID],
    references: [media.id],
    relationName: 'media',
    }),
    'guest-sessionsID': one(guest_sessions, {
    
    fields: [payload_locked_documents_rels['guest-sessionsID']],
    references: [guest_sessions.id],
    relationName: 'guest-sessions',
    }),
    listsID: one(lists, {
    
    fields: [payload_locked_documents_rels.listsID],
    references: [lists.id],
    relationName: 'lists',
    }),
    tasksID: one(tasks, {
    
    fields: [payload_locked_documents_rels.tasksID],
    references: [tasks.id],
    relationName: 'tasks',
    }),
    'task-logsID': one(task_logs, {
    
    fields: [payload_locked_documents_rels['task-logsID']],
    references: [task_logs.id],
    relationName: 'task-logs',
    }),
    'focus-sessionsID': one(focus_sessions, {
    
    fields: [payload_locked_documents_rels['focus-sessionsID']],
    references: [focus_sessions.id],
    relationName: 'focus-sessions',
    }),
      }))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
      }))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_migrations = relations(payload_migrations, () => ({
  
      }))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  guest_sessions: typeof guest_sessions
  lists: typeof lists
  tasks_subtasks: typeof tasks_subtasks
  tasks: typeof tasks
  task_logs: typeof task_logs
  focus_sessions: typeof focus_sessions
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_guest_sessions: typeof relations_guest_sessions
  relations_lists: typeof relations_lists
  relations_tasks_subtasks: typeof relations_tasks_subtasks
  relations_tasks: typeof relations_tasks
  relations_task_logs: typeof relations_task_logs
  relations_focus_sessions: typeof relations_focus_sessions
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}
    

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
    